version: '3'

services:

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9999 app.js
    ports:
      - "80:8080"
      - "9999:9999"
      - "7357:7357"
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  notused: